/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SedeRouteImport } from './routes/sede'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as GalleriaRouteImport } from './routes/galleria'
import { Route as EventiRouteImport } from './routes/eventi'
import { Route as DisciplineRouteImport } from './routes/discipline'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SedeRoute = SedeRouteImport.update({
  id: '/sede',
  path: '/sede',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriaRoute = GalleriaRouteImport.update({
  id: '/galleria',
  path: '/galleria',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/discipline': typeof DisciplineRoute
  '/eventi': typeof EventiRoute
  '/galleria': typeof GalleriaRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/sede': typeof SedeRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/discipline': typeof DisciplineRoute
  '/eventi': typeof EventiRoute
  '/galleria': typeof GalleriaRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/sede': typeof SedeRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/discipline': typeof DisciplineRoute
  '/eventi': typeof EventiRoute
  '/galleria': typeof GalleriaRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/sede': typeof SedeRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contatti'
    | '/cookie'
    | '/discipline'
    | '/eventi'
    | '/galleria'
    | '/manifesto'
    | '/privacy'
    | '/sede'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatti'
    | '/cookie'
    | '/discipline'
    | '/eventi'
    | '/galleria'
    | '/manifesto'
    | '/privacy'
    | '/sede'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/contatti'
    | '/cookie'
    | '/discipline'
    | '/eventi'
    | '/galleria'
    | '/manifesto'
    | '/privacy'
    | '/sede'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContattiRoute: typeof ContattiRoute
  CookieRoute: typeof CookieRoute
  DisciplineRoute: typeof DisciplineRoute
  EventiRoute: typeof EventiRoute
  GalleriaRoute: typeof GalleriaRoute
  ManifestoRoute: typeof ManifestoRoute
  PrivacyRoute: typeof PrivacyRoute
  SedeRoute: typeof SedeRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sede': {
      id: '/sede'
      path: '/sede'
      fullPath: '/sede'
      preLoaderRoute: typeof SedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleria': {
      id: '/galleria'
      path: '/galleria'
      fullPath: '/galleria'
      preLoaderRoute: typeof GalleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline': {
      id: '/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContattiRoute: ContattiRoute,
  CookieRoute: CookieRoute,
  DisciplineRoute: DisciplineRoute,
  EventiRoute: EventiRoute,
  GalleriaRoute: GalleriaRoute,
  ManifestoRoute: ManifestoRoute,
  PrivacyRoute: PrivacyRoute,
  SedeRoute: SedeRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
